---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: kashaik
    type: db
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
...



